title:       "Eric Emillan"
email:       your.email@example.com
description: "Geospatial Coordinator & Blogger"
baseurl:     ""  
url:         "https://<your-username>.github.io"

theme:       minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
